# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20180424_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='test text for question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
            preserve_default=False,
        ),
    ]
